apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-web
  labels:
    app: productpro-web
spec:
  replicas: {{ .Values.replicaCountWeb }}
  selector:
    matchLabels:
      app: productpro-web
  template:
    metadata:
      labels:
        app: productpro-web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageWeb.repository }}:{{ .Values.imageWeb.tag }}"
          imagePullPolicy: {{ .Values.imageWeb.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            # API server URL
            - name: prop.api.server.url
              valueFrom:
                configMapKeyRef:
                  name: productpro-config-map
                  key: prop.api.server.url
            - name: ENV_API_SERVER_URL
              value: {{ .Values.apiServerUrl }}