apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-web
  labels:
    app: {{ template "productpro-app-helm-charts.name" . }}
    chart: {{ template "productpro-app-helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCountWeb }}
  selector:
    matchLabels:
      app: {{ template "productpro-app-helm-charts.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "productpro-app-helm-charts.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageWeb.repository }}:{{ .Values.imageWeb.tag }}"
          imagePullPolicy: {{ .Values.imageWeb.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
