apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-web
  labels:
    app: {{ template "productpro-app-helm-charts.name" . }}
    chart: {{ template "productpro-app-helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceWeb.type }}
  ports:
    - name: http
      protocol: TCP
      nodePort: {{ .Values.serviceWeb.nodePort }}
      targetPort: {{ .Values.serviceWeb.targetPort }}
      port: {{ .Values.serviceWeb.port }}
  selector:
    app: {{ template "productpro-app-helm-charts.name" . }}
    release: {{ .Release.Name }}
