apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-s-image-pull-secret
  labels:
    app: {{ template "productpro-app-secured-helm-charts.name" . }}
    chart: {{ template "productpro-app-secured-helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerImagePullSecretValue }}

####  Generate dockerconfigjson using the below command
# Here namespace and myname are not used during the encryption
# kubectl create secret docker-registry myname --docker-server=mycluster.icp:8500 --docker-username=admin --docker-password=admiiinnnn --docker-email=null  --dry-run -o yaml
