FROM anapsix/alpine-java:8
WORKDIR /
ADD target/product-web-0.0.1-SNAPSHOT.jar productpro-web.jar
RUN sh -c 'touch /productpro-web.jar'
EXPOSE 80
ENTRYPOINT ["java","-jar","/productpro-web.jar"]

FROM open-liberty:springBoot2 as staging
COPY --chown=1001:0 target/product-web-0.0.1-SNAPSHOT.jar /staging/myFatApp.jar
RUN springBootUtility thin \
 --sourceAppPath=/staging/myFatApp.jar \
 --targetThinAppPath=/staging/myThinApp.jar \
 --targetLibCachePath=/staging/lib.index.cache
FROM open-liberty:springBoot2
COPY --from=staging /staging/lib.index.cache /lib.index.cache
COPY --from=staging /staging/myThinApp.jar /config/dropins/spring/productpro-web.jar