apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-web
  labels:
    app: {{ template "productpro-web.name" . }}
    chart: {{ template "productpro-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "productpro-web.name" . }}
    release: {{ .Release.Name }}
